#%RAML 1.0 NamedExample

value:
  songTitle: "The heart wants what it wants"
  artist: {
    artistId: "1",
    artistName: "Selena Gomez"
  }
  album: {
    albumId: "1",
    albumName: "The StarGirl"
  }