#%RAML 1.0 Trait

description: Apply this trait to any method that needs to have search functionality.

queryParameters:
  query:
    description: JSON array [{"field1", "value1", "operator1"}, ..., {"field1", "value1", "operator1"}]  <<description>>
    example: <<example>>